### ISSUE TITLE
slow code

### ISSUE THREAD

**Issue by fahim-foysal-097** [fahim-is-zero/ProjectEulerSolutions#1]
**[problem-014](https://github.com/fahim-is-zero/ProjectEulerSolutions/blob/main/Python/problem-014(slow).py)** is [_slow_.] Takes almost **15+** seconds to run the code.

**Comment by fahim-is-zero** [comment]
new updated faster version [here](https://github.com/fahim-is-zero/ProjectEulerSolutions/blob/main/Python/problem-014.py)

**Comment by fahim-foysal-097** [comment]
new updated faster version [here](https://github.com/fahim-is-zero/ProjectEulerSolutions/blob/main/Python/problem-014.py)
